spring:
  profiles:
    active: local
  application:
    name: wow-libre-transaction
  jackson:
    property-naming-strategy: SNAKE_CASE
management:
  endpoints:
    web:
      exposure:
        include: health
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: ${DB_TRANSACTION_HOST:jdbc:mysql://localhost:3306/transactions}
    username: ${DB_TRANSACTION_USERNAME:root}
    password: ${DB_TRANSACTION_PASSWORD:sebastian}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /transaction
  address: 0.0.0.0
  port: ${TRANSACTION_SERVER_PORT:8092}
application:
  urls:
    wow-libre: ${HOST_BASE_CORE:http://localhost:8091/core}
    payu: ${PAYU_API_URL:https://sandbox.api.payulatam.com/reports-api/4.0/service.cgi}
  signature:
    secret-key: ${APP_SIGNATURE_SECRET_KEY:your-secret-key-change-in-production}
  security:
    jwt:
      secret-key: ${CORE_JWT_SECRET_KEY:6E4D574873506B4A72434B6A614B39786F736B7855666B4D456A6E466F785572}
      expiration: 604800000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: ${DB_TRANSACTION_HOST}
    username: ${DB_TRANSACTION_USERNAME}
    password: ${DB_TRANSACTION_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /transaction
  address: 0.0.0.0
  port: ${TRANSACTION_SERVER_PORT:8092}
application:
  urls:
    wow-libre: ${HOST_BASE_CORE}
    payu: ${PAYU_API_URL:https://api.payulatam.com/reports-api/4.0/service.cgi}
  signature:
    secret-key: ${APP_SIGNATURE_SECRET_KEY}
  security:
    jwt:
      secret-key: ${CORE_JWT_SECRET_KEY}
      expiration: 604800000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
