spring:
  profiles:
    active: local
  application:
    name: wow-libre-transaction
  jackson:
    property-naming-strategy: SNAKE_CASE
management:
  endpoints:
    web:
      exposure:
        include: health
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/transactions
    username: root
    password: Wowlibre96@@
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /transaction
  address: 0.0.0.0
  port: 8092
application:
  urls:
    wow-libre: http://localhost:8091/core
  account:
    username: play4chitiva@gmail.com
    password: 'sebas'
  payu:
    host: https://sandbox.checkout.payulatam.com/ppp-web-gateway-payu/
    api-key: '4Vj8eK4rloUd272L48hsrarnUA'
    api-login: 'VZi8TSkE885mNUO'
    key-public: 'PK78h9R8Kb0Ij4v7qA616L363y'
    url-confirmation: "https://67a3-191-107-231-157.ngrok-free.app/transaction/api/payment/notification"
    merchant-id: '508029'
    account-id: '512321'
    is-test: "1"
  security:
    jwt:
      secret-key: 6E4D574873506B4A72434B6A614B39786F736B7855666B4D456A6E466F785572
      expiration: 604800000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /transaction
  address: 0.0.0.0
  port: 8092
application:
  urls:
    wow-libre: ${WOW_LIBRE_HOST}/core
  account:
    username: ${WOW_LIBRE_USERNAME}
    password: ${WOW_LIBRE_PASSWORD}
  payu:
    host: https://checkout.payulatam.com/ppp-web-gateway-payu/
    api-key: 'b2FBMrt2FoKo1kFMXS87rt4LCr'
    api-login: 'VZi8TSkE885mNUO'
    key-public: 'PK78h9R8Kb0Ij4v7qA616L363y'
    url-confirmation: https://api.wowlibre.com/transaction/api/payment/notification
    merchant-id: '1019523'
    account-id: '1028547'
    is-test: "0"
  security:
    jwt:
      secret-key: ${SECRET-KEY}
      expiration: 604800000 # a day
      refresh-token:
        expiration: 604800000 # 7 days